default: &default
  database:
    user: <%= ENV["SUPPORT_SQL_USER"] %>
    password: <%= ENV["SUPPORT_SQL_PASSW"] %>

  mailer: &mailer
    domain_name: <%= ENV["DOMAIN_NAME"]%>

    mailgun_hostname: <%= ENV["MAILGUN_HOSTNAME"]%>
    
    mailgun_hostname: <%= ENV["MAILGUN_HOSTNAME"]%>

    mailgun_user: <%= ENV["SUPPORT_MAILGUN_USER"]%>
    mailgun_password: <%= ENV["SUPPORT_MAILGUN_PASSW"] %>
    mailgun_api_key: <%= ENV["SUPPORT_MAILGUN_API_KEY"] %>
 
  secret_key_base: <%= ENV["SUPPORT_SECRET_KEY_BASE"]%>


development:
  <<: *default
  mailer:
    <<: *mailer
    domain_name: 'support.l-plan.nl'
test:
  <<: *default

production:
  <<: *default
