default: &default
  database:
    user: <%= ENV["SUPPORT_SQL_USER"] %>
    password: <%= ENV["SUPPORT_SQL_PASSW"] %>

  mailer: &mailer
    domain_name: <%= ENV["DOMAIN_NAME"]%>

    mailgun_hostname: <%= ENV["MAILGUN_HOSTNAME"]%>

    mailgun_user: <%= ENV["SUPPORT_MAILGUN_USER"]%>
    mailgun_password: <%= ENV["SUPPORT_MAILGUN_PASSW"] %>
    mailgun_api_key: <%= ENV["SUPPORT_MAILGUN_API_KEY"] %>
 
  secret_key_base: <%= ENV["SUPPORT_SECRET_KEY_BASE"]%>


development:
  google_client_id: 1032949297619-5nqftn8e540bnohtqjiv3pg2qvg7uvtj.apps.googleusercontent.com
  google_client_secret: 1L43_SExBR35OHLi4jnLOkzr
  recaptcha_site_key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  recaptcha_secret_key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

development:
  <<: *default
  mailer:
    <<: *mailer
    domain_name: 'support.l-plan.nl'
test:
  <<: *default
  google_client_id:
  google_client_secret:
  recaptcha_site_key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  recaptcha_secret_key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe


production:
  <<: *default
  google_client_id:
  google_client_secret:
  recaptcha_site_key:  <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

